//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

int main() {
    int last = 1; // Last Fibonacci number
    int second_last = 1; // Second last Fibonacci number
    int nextFibonacci = 0; // Next Fibonacci number
    int fibonacciSum = 0; // Sum of even Fibonacci numbers

    while (nextFibonacci < 4000000) {
        nextFibonacci = last + second_last; // Calculate next Fibonacci number

        if (nextFibonacci % 2 == 0) { // Check if it is even
            fibonacciSum += nextFibonacci; // Add to the sum
        }

        second_last = last; // Update second last
        last = nextFibonacci; // Update last
    }

    printf("The sum of even Fibonacci numbers less than 4,000,000 is: %d\n", fibonacciSum);
    return 0;
}
