#!/usr/bin/python3
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

#NOTE - there's gotta be smarter ways to do this than just building these massive lists and looking them up but once again, eh.
#Coded this in under 5 minutes.  Humans are expensive, computers are cheap.

triangleList = []
pentagonList = []
hexagonList = []

#Build a list of triangular numbers
for n in range(1,100000):
    triangleList.append(int(n*((n+1))/2))

#Build a list of pentagonal numbers
for n in range(1,100000):
    pentagonList.append(int(n*((3*n)-1)/2))

#Build a list of hexagonal numbers
for n in range(1,100000):
    hexagonList.append(int(n*((2*n-1))))

for triangle in triangleList:
    #See if it's in both other lists, also ignore 1 and our problem example
    if triangle in pentagonList and triangle in hexagonList and triangle != 1 and triangle != 40755:
        print(f"The next triangle number that's also pentagonal and hexagonal is: {triangle}")
        quit()